apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-zero-spring-petclinic
  labels:
    app: product-zero-spring--petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-zero-spring-petclinic
  template:
    metadata:
      labels:
        app: product-zero-spring-petclinic
    spec:
      containers:
      - name: product-zero-spring-petclinic
        image: pwcinfradockerrg.azurecr.io/springboot-petclinic-actions:v1
        ports:
        - containerPort: 8080




