apiVersion: v1
kind: Service
metadata:
  name: product-zero-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetport: 8080
    protocol: TCP
    name: http
  selector:
    app: product-zero-spring--petclinic